[package]
name = "sandbox"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pref = { path = "../pref" }
tokio = { version = "1.38" }
axum = "0.7"
log = "0.4"
simple_logger = "4"